### ISSUE TITLE
France is going Communist in the early game

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#1]
France is going Communist frequently very early in the game, well before it could have gone that route in the focus tree - and sometimes even when it has gone a contradictory route.

**Comment by Greatexperiment** [comment]
This might be a vanilla issue - since political switches are now handled by decisions

**Comment by Greatexperiment** [comment]
This hasn't been observed in a while. Time to close issue #1!

**Comment by Thinking-waffle** [comment]
It may also have been caused by the lacking restrictions of the french trees as you removed/ignored them
In addition I have changed that event about the communists removing their support of the popular front.

**Comment by Greatexperiment** [comment]
What restrictions are those? There should be historical checks in place for the major political focuses, unless they somehow got imploded.
