### ISSUE TITLE
The formation of vichy puppet free france

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#100]

**Comment by Zurich899** [comment]
After a bit of research, I learned that Vichy Free forms through a civil war, and that the civil war which creates Vichy was removed from R56's event file (no idea why). I did some testing, and adding the civil war command back to the file makes Vichy work correctly.

**Comment by Greatexperiment** [comment]
It's because it was causing errors and CTD issues due to some modded content that Waffle needs to update. So it was temporarily removed until it's fixed. However, this removal wasn't very graceful and was meant to just be a quick fix.
