### ISSUE TITLE
Mass Assualt doctorine rework?

### ISSUE THREAD

**Issue by Ben3874** [deliciousmods/1956_beta#101]
This is a suggestion/enhancment
I've been playing the soviet union a bunch recently, and here's my thoughts:

- Mass assualt tree is unbelievably trash, atleast have the infantry combat width at -0.6, that way you can achieve 20 width divisions with artillary. 
This applies to all countries. The rest only apply to the soviets.

- Allowing Women into the army should not be 10% recruitable pop, seems op, perhaps disperse the recruitable pop focuses?
- The focuses after purge and before lessons of war are completley useless focuses
- The +50% time to war justification seems a bit excessive, yes they're strong earlygame, but like every nation they should be able to expand a little bit (Maybe 20/25%?)
- Infanstructure focus for fighting in the east now that Japan has been buffed? Fighting there is a complete pain due to the Japanese stacked bonuses and low supply.

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
