### ISSUE TITLE
Fixes to Broken Estonia Focuses 

### ISSUE THREAD

**Issue by SpicyAlfredo** [deliciousmods/1956_beta#124]
"attempted bug fixes to two broken focuses in the Estonia Focus tree."

-Fixes bad state references in EST_air_base_expansion. Now builds air bases in Estonia clay. Now prioritizes starting provinces (191) and (13). 
-Fixes bad state references in EST_air_base_expansion completed tool tip. Will now say airfields where built in (191) and (13) "Band aide fix, if the focus builds air bases in clay other then (191) and (13) the tool tip will be wrong" 
-Fixes EST_expand_port_paldiski not granting dockyards upon compilation 

[est.txt](https://github.com/deliciousmods/1956_beta/files/1896702/est.txt)

**Comment by Greatexperiment** [comment]
thanks.
