### ISSUE TITLE
Ugh

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#131]
user quote:

No idea if this is a bug but it seems like it. Bulgaria's AI seems to be acting pretty peculiar. It started when I tried play a game as Greece for the first time. Bulgaria rushed down it's focus tree to the Tripartite Pact, demanded Thrace, declared war, and called Germany into the war. The Romanians rushed them from the north (since they had stacked all their troops along my border) and quickly capitulated. Couldn't have been more than a week or two but now me an Romania were in a war with Germany, who later called Italy in once they joined the Axis, and summarily invaded me. I tried again, being a bit more prepared for the German and Italian invasion and managed to survive, but being pulled into a war so early makes it difficult to do all the cool Greek things. Bulgaria later became a democratic puppet after a peace deal I didn't have a say in, which was extra frustrating. 

However, I discovered another problem after swapping over Romania to see what fun I could have there. Bulgaria demanded Dobruja, but declining gives them a war goal against Greece for Istanbul, which is controlled by Turkey. They also decided they wanted the national focus for communism.

https://i.imgur.com/VM3sKVZ.png Hovering over the refuse option shows the event being triggered
https://i.imgur.com/VP2P8Lk.png Bulgaria's peculiar war goal
https://i.imgur.com/90Z2J6A.png Istanbul still belongs to Turkey, not Greece like the previous wargoal would suggest.
https://i.imgur.com/GvwkQ7P.png Bulgaria going along the focus tree that gives the communist party growth, when they've already joined the Axis

In the event that the Colored Buttons mod might be affecting the game, I turned it off, as it was the only other mod I had enabled, then I started a game as Greece and got pretty much the same results.

https://i.imgur.com/S5LKdnp.png Bulgaria demands Thrace immediately after having joined the Axis in 1936
https://i.imgur.com/SUb0Fxk.png I refuse, naturally. 
https://i.imgur.com/l2igCwu.png They stack their troops on my border
https://i.imgur.com/FIlqTou.png They declare war and call in the germans as their ally. You can see Romania already moving into Bulgaria because there's no troops to stop them.
https://i.imgur.com/DWF9pu2.png Bulgaria capitulates about two weeks after the war begins.
https://i.imgur.com/jKGlwIi.png The war won't end since Germany is called in, and there's no event or decision in the game currently to peace out with Germany.
https://i.imgur.com/fcWbde8.png Also, Bulgaria still tries to get that communist influence going.

**Comment by Zurich899** [comment]
I'm trying to reproduce this user's issues right now. I can't reproduce Greece getting the "Demand Dobrudja" event, it's going to Romania as expected.

**Comment by Zurich899** [comment]
Thanks for the merge. Now that everything which could be reproduced has been fixed, I think that this issue can be closed.
