### ISSUE TITLE
Fix the chinese generals created through events

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#136]
Chinese warlords can be used by KMT china but it creates new generals but they don't have avanced stats and new portraits. It should probably use the transfer commander command anyway now that it's available, so either add tag for the chinese generals or create traits to identify the warlords generals, some custom effects could be fun. I have an idea actually, they could have a background about their region of origin and have a bonus in their regional core territories. That way their regional nature would be reinforced and it could be used to identify their origin. Wait I don't know if you can link an effect to foreign core.

**Comment by Greatexperiment** [comment]
This likely applies to a lot of generals - in general.

**Comment by Tyguy9112** [comment]
Reply, if issue reoccurs.
