### ISSUE TITLE
Invisible Enemy Division Icons

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#14]
User Quote:

For some reason, became unable to see division icons for Japan, which made the prospect of war troubling. Reloading the save did nothing, but restarting the game entirely fixed the issue. The bug also applied to Guangxi Clique, as I had previously declared war on them for a hypothetical "what-if" before reloading that save (taking place before the war against Japan, but I reloaded to before it happened). Assuming that this would have applied to all nations, but didn't think to check before I restarted the game. Unsure of parameters necessary to replicate.

Addendum 1: Issue replicated, current hypothesis is that it occurs when loading a save without restarting the game.

Addendum 1.1: I alt-tabbed back into the game, and by the time I finished typing up Addendum 1, it started working as intended with no issue. This did not occur the first time the bug showed, as I had tabbed in and out several times. I am confused, but leaving the note as-is.

Addendum 1.2: Bug has not been replicated since those two occurrences.

**Comment by Greatexperiment** [comment]
unable to verify, and sounds like something related to vanilla
