### ISSUE TITLE
RAJ is missing focus names

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#145]
Not sure why atm, but will look into it later.

**Comment by SpicyAlfredo** [comment]
Lacks unique mod localization file maybe?

**Comment by Greatexperiment** [comment]
These two focuses rely on scripted localization. In an earlier patch all the local scripts were removed because they were causing 100+ broken focus errors which were impractical to manually fix. 

I've partially enabled some of it back though, so that the focus names for RAJ are visible as intended.
