### ISSUE TITLE
Tweak ET Tech values

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#147]
The values in the tree are inconsistent and also so small as to be virtually worthless.

**Comment by Thinking-waffle** [comment]
and the first uniform tech is basically the invention of clothing, apart from Ethiopia and Tibet (outside of the Guard of the Dalai Lama) and Finland in case of a rapid extended conscription, everybody had that.

**Comment by Greatexperiment** [comment]
They should probably start off with it by default, and the tech renamed to "Great War Uniforms"

**Comment by Greatexperiment** [comment]
Note to self - add in upgrade improvements instead of regular bonuses for some techs.

**Comment by Greatexperiment** [comment]
SRD tech has weird bonus.

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
