### ISSUE TITLE
Fascists March on Shanghai

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#15]
User Comment:

Event ID = political.21
No referendum was held, yet there was a civil war anyways. The Fascist party, Blueshirts, had 78% support, and I was planning on making the swap to Fascism using the referendum Decision. However, I didn't have the opportunity, and so a civil war started more or less unheard of. This may be a part of how things work with the new DLC (forcing the player to use the Decision immediately when possible), or it might be a bug. Unsure if big, but likely easy to replicate. Loading to previous save file, as this is something that would normally be avoided had I known it was possible.

**Comment by Tyguy9112** [comment]
Reply, if issue reoccurs.
