### ISSUE TITLE
Kurdistan

### ISSUE THREAD

**Issue by ronim-efrin** [deliciousmods/1956_beta#1561]
Please add a focus tree or something to Kurdistan, i tried playing as them and it was super boring after i annexed turkey. And Kurdistan is a great opportunity, they have a wide history, many separatists and religious activities. For example, they were supporting the massacre of armenia in the ottoman times, (they apologized). Maybe you can add an event about that, that was just an example ofc. But there is much more, as what language or religion. The yezidi seperatists for example, seperating themselves from the kurds and calling them selves yezidis. There was a kurdish state in the soviet union but Stalin dispanded it, they use 3 diffrent widley known alphabets, cyrellic, latin(main) and persian. My friend recommended that i should file an issue, so i decided to do it.

**Comment by TheBrit7** [comment]
Would you like to supply any sources we could use?

**Comment by ronim-efrin** [comment]
> Would you like to supply any sources we could use?

You should be more specific lol, i linked all the sources i used to write. 

you can ask if you want anything specific, like operation mammoth where Nazi Germany promised the kurds an independent state. : https://en.wikipedia.org/wiki/Operation_Mammoth

https://en.wikipedia.org/wiki/List_of_Kurds
_**Saladin is the most notable one**_

https://en.wikipedia.org/wiki/List_of_Kurdish_dynasties_and_countries

https://en.wikipedia.org/wiki/Kurdistansky_Uyezd

https://en.wikipedia.org/wiki/Kurdish_languages
**Kurds and their language are Indo-European.**

https://en.wikipedia.org/wiki/Kurdish_alphabets

https://en.wikipedia.org/wiki/Kurds

https://en.wikipedia.org/wiki/Kurdish_culture

https://en.wikipedia.org/wiki/Kurdish_recognition_of_the_Armenian_genocide#:~:text=There%20is%20a%20recognition%20by,participated%20in%20massacres%20of%20Armenians.

https://en.wikipedia.org/wiki/Kurdish_literature

https://en.wikipedia.org/wiki/History_of_the_Kurds

https://en.wikipedia.org/wiki/1935_Yazidi_revolt

https://kurdishpeople.org/red-kurdistan/

https://www.institutkurde.org/en/

Ancient Kurdish religions dating to the times before Zoroastrianism: 
https://en.wikipedia.org/wiki/Melek_Taus
https://en.m.wikipedia.org/wiki/Yazd%C3%A2nism
https://en.wikipedia.org/wiki/Yazidis

And if you would like everything in video form: https://youtube.com/c/EverythingaboutKurdistan

**Comment by ronim-efrin** [comment]
Us kurds believe that we are the sons of Cyrus, Darius and Xerxes I; Medes and Achaemenid empire, it's even in our national song. This is not confirmed, it is doubted and believed by many historians. But note that this definitely isn't the beginning of our history, it goes far back before that time.

**Comment by ronim-efrin** [comment]
Kurdish roots and history are deep but not as well documented as central European history or Christianity. There will be a lot of uncertainties when researching.
