### ISSUE TITLE
Indonesia Independence

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#159]
user quote:

Is there is reason why the dutch east indies is becoming free in a year and why its counrty autonomy is growing at 1 point a day your mod is the only one i have installed!!!!

**Comment by Thinking-waffle** [comment]
I confirm it, I have mentionned it to Skip before it should be other way around. he tried something unique but it's simply not working.

**Comment by Zurich899** [comment]
In my last game in R56, Indonesia sped its way to independence, despite going down the "stay loyal" branch. I can understand going free quickly if you go fascist (Japanese assistance) or communist (soviet assistance), but Indonesia should stay an integrated puppet (or at least puppet) until 1945 if they decide to stay loyal. I'll take a look at its tree and events and nerf some of the autonomy gain, especially in the "stay loyal" branch.

**Comment by Thinking-waffle** [comment]
Instead give me directives on what you suggest to change, because I am integrating it closer with the new dutch tree.

**Comment by Thinking-waffle** [comment]
Skip, you can join the discussion too btw, you should be the first to be concerned by this.

**Comment by Zurich899** [comment]
Fair enough. I'm fine with the fascist and communist branches being quick paths to independence, although I think that having events or decisions for Indonesia's independence if it is occupied by Japan (which is how it happened historically) could be a good idea. This tree strangely has Sukarno as the fascist leader, which makes sense during the Japanese occupation (since he and Mohammad Hatta collaborated with the Japanese), but someone else should be the fascist leader if Indonesia is independent. After the war, I think Indonesia should have a choice between Sukarno's unitary (pancasila) system (non-aligned ideology would be appropriate) or Hatta's proposed federal system (democratic)

**Comment by Zurich899** [comment]
While you're making the new Dutch focus tree, I think some focuses for developing Indonesia (adding infrastructure, resources, and civilian factories) which lower the East Indies' autonomy would be great (similar to what the UK has for its dominions). The Dutch built several railways in Java and Sumatra before Indonesia's independence. As for independence itself, The East Indies should be able to declare independence if the Netherlands capitulates, or if they're occupied by Japan. If the Netherlands is restored, they can have an option to retake Indonesia or not. If they choose to invade, Indonesia could have an option for peace if they can hold their core territory for a year (I could make a variation of my Honduras peace decisions for that if you like)

**Comment by Zurich899** [comment]
Sorry, that turned into a bit of a novel, but I'm pretty familiar with Indonesian history because I'm studying abroad in that country right now. If you ever want to talk more about ideas for that country, just let me know).

**Comment by Thinking-waffle** [comment]
you can put a max of ideas in the waffle workshop section, don't forget to tag skip about it. I will read that tomorrow

**Comment by Thinking-waffle** [comment]
and don't be sorry that's how immersive focuses are done

**Comment by Zurich899** [comment]
Alrighty, I'll just copy what I wrote here into your channel so that you can look at it more quickly

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
