### ISSUE TITLE
Itamaraty Brazil

### ISSUE THREAD

**Issue by Ubus99** [deliciousmods/1956_beta#1704]
The Itamaraty focus in the Brazil Tree requires one of 5 political foci to be completed.
I chose to go for communism, but because I archived the revolution peacefully without using the focus I am now locked out of all further foci on that tree and Itamary.
I don't know if the same thing happens with the other foci required for itamaty, but I would suggest adding a bypass option to them.

**Comment by ilkober** [comment]
Added bypass conditions in case Vargas is not in power
