### ISSUE TITLE
Integrate Honduras

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#172]

**Comment by Greatexperiment** [comment]
1. Add # Extended Technologies - etax_doctrine, camo to HON History file.
2. Add set_stability and research slots to HON History file.
3. Merge 'replace_l_english' into r56_parties
4. Remove generic continuous focus set, specify cf position in national focus file.
5. Remove cosmetic countries file. Needs a HON specific color file + 56 merge.
6. Merge interface, bookmarks, techs, opinion modifiers into equivalents.
7. Needs AI_focus file.
8. Needs to use sanity AI scripts in national focus.
9. Consider using 'target = global_event_target:r56_state_owner_ID' system for flexible war declarations.
10. Needs HON unit history file.
11. Check indents and spacing in a number of files.

**Comment by Zurich899** [comment]
Since all of the files you asked for were added, we could close this issue as soon as the old honduras.txt national focus file is deleted (https://github.com/deliciousmods/1956_beta/pull/209)
