### ISSUE TITLE
Invalid Scope

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#173]
[12:37:00][effect.cpp:411]: Error in effect:set_country_flag: Invalid Scope
[12:37:00][trigger.cpp:242]: Error in trigger:: Invalid Scope

This is likely from one of the recent additions. It's also going to be a pain to find.

**Comment by Zurich899** [comment]
Odd, I don't have those lines in my error log when loading the beta. I just have a lot of text about missing ideas (which are from the War at Sea mod, I think).
[error.log](https://github.com/deliciousmods/1956_beta/files/1949607/error.log)

**Comment by Greatexperiment** [comment]
There shouldn't be any errors associated with the TWAS stuff - even if it is incomplete at the moment. The scope error appears when the game is fully loaded after selecting a country.

**Comment by Zurich899** [comment]
Ah, I see what you mean. After I loaded a country I saw it too. I'll try looking for it by working through the latest commits, but you're right, it's definitely a needle in a haystack.

**Comment by Zurich899** [comment]
This really is a pain to find. But I can confirm it's not in the TWAS, new France, or Honduras event files, since I tried deleting them in my local beta and still got that error.

**Comment by Zurich899** [comment]
And it's not in any of the event files. I deleted literally everything in the events folder but still got that error. What uses triggers, other than events?

**Comment by Greatexperiment** [comment]
🥇
