### ISSUE TITLE
Game Crash when playing any Axis nation

### ISSUE THREAD

**Issue by Treep3r** [deliciousmods/1956_beta#1832]
So a friend and I have been playing Rt56 a lot recently. 
We've started to run into quite a bunch of crashing around the year 1942 when playing as any Axis nation.
No matter if we use some small mods in addition or just pure Rt56.
We played Japan in Coop, it crashed mid 1942.
We played Germany in Coop, also crash around the same time.
Today we tried Germany, Italy and Poland in Axis, and again, crash early 1942.

However playing Coop as USA worked just fine, got to 1945 and beyond.
Playing USA and Britain also worked fine.

I am pretty desperate as we pour so much time into these saves just for them to be corrupted after a certain point.

Here's the error log of the latest crash, I can't really make much of it. 
I don't know why it says it can't find certain mod files for mods I do not have installed.
However all the crashreports are basically the same.
[error.log](https://github.com/deliciousmods/1956_beta/files/6871431/error.log)

I really hope that someone can help me here, as Rt56 is probably the best mod there is out there.

**Comment by Treep3r** [comment]
Update.
It seems to be AI controlled USA that's causing the crash.

**Comment by Treep3r** [comment]
Alright, we just confirmed it, we can rescue the saves by having someone play as USA for a month for the time of the crash.

**Comment by Treep3r** [comment]
Further Update.
It doesn't seem to be limited to the USA.
This time the same thing happened whith the British Raj.
[error.log](https://github.com/deliciousmods/1956_beta/files/6879458/error.log)

It was again fixed by having a player play as the Raj for a couple months.

**Comment by VictorBesson** [comment]
To help, i have the same crash, in the same date, with the same error :
`[navalmission.cpp:1947]: TaskForce in province id 4611 that has no sea access`

**Comment by marijn211** [comment]
> To help, i have the same crash, in the same date, with the same error :
> `[navalmission.cpp:1947]: TaskForce in province id 4611 that has no sea access`

Known and most likely fixed issue

**Comment by Lindorn** [comment]
Weve had the same problem.  Have solved it by deleting all the ships in the port at least temporarily.  Your logs helped us identify the issue, thanks.

**Comment by Shizophrener** [comment]
Fixed on dev version
