### ISSUE TITLE
Game crashes during "total war"

### ISSUE THREAD

**Issue by djcrazyone** [deliciousmods/1956_beta#1836]
Hello!

I have been having issues with the game crashing, just tried a go only with r56 on, and sadly it still happened.
I hope the error log will help locate the issue

[error.log](https://github.com/deliciousmods/1956_beta/files/6880818/error.log)

**Comment by djcrazyone** [comment]
I jumped into observe and found a "fleet" that was detatched, from USA, reparing in state 4611, or trying to leave the port there. Took control of USA and deleted the single ship, and game has been running past the crash date.

Is this game issue or mod?

**Comment by marijn211** [comment]
Known issue that is most likely already fixed but thanks for report
