### ISSUE TITLE
Game Breaking Naval Bug

### ISSUE THREAD

**Issue by HindusPL** [deliciousmods/1956_beta#1837]
Around 1940 At the panama province 4611 an error starts to happen:

[navalmission.cpp:1947]: TaskForce in province id 4611 that has no sea access

Then this error begins to happen hundreds of times in a single day until it overloads the game and makes it crash. 

Players can only fix this by deleting all the ships from the naval base in province 4611. 

The error begins again when ships go to dock there. 

Please fix this as it is making all my games stop at 40-43. 

Some other people are also experiencing this:
https://www.reddit.com/r/hoi4/comments/oivzw8/crashing_issue_reposted/

[The Error log With the error And when the error stops due to the ships being deleted from the naval base.txt](https://github.com/deliciousmods/1956_beta/files/6889925/The.Error.log.With.the.error.And.when.the.error.stops.due.to.the.ships.being.deleted.from.the.naval.base.txt)

**Comment by Lindorn** [comment]
Weve had the same problem.  Fix it by deleting all ships in that port. (at least temporarily)
