### ISSUE TITLE
Colombia gains claim on South Carolina for no reason

### ISSUE THREAD

**Issue by SirGorwyd** [deliciousmods/1956_beta#1848]
Forming Gran Colombia currently requires gaining control of South Carolina, rather than Northern Panama as I believe was the intention. Makes no sense currently to have to invade the US on a suicide mission.

Also Colombia doesn't get an infantry OR armor expert which drives me up the wall but I'll live.

**Comment by TheBrit7** [comment]
This bug has been reported and fixed, wait for the next patch.
