### ISSUE TITLE
Game Crashes due to TaskForce in province id 4611 that has no sea access

### ISSUE THREAD

**Issue by rubrical-works** [deliciousmods/1956_beta#1850]
RT 56 crashes in late game with error: TaskForce in province id 4611 that has no sea access. I have seen this posted elsewhere as well. It seems to be specifically associated with RT56. 

Please let me know what else is required (crash logs, game file, etc)

**Comment by Shizophrener** [comment]
Fixed in the beta

**Comment by rubrical-works** [comment]
Do you have the commit number for this fix?

And does this required abandoning the current game when the subscription is updated?

**Comment by Shizophrener** [comment]
Here's the PR https://github.com/deliciousmods/1956_beta/pull/1824.

Save game should work with a few additional bugs.

**Comment by rubrical-works** [comment]
Thanks - I added the buildings and proceeded past the crash point. 

On my way to world domination...er...spreading the word about democracy that is...

Interestingly, Italy never joined the axis is this particular game.
