### ISSUE TITLE
Suggest changing Perez Jimenez' portrait

### ISSUE THREAD

**Issue by hurafloyd** [deliciousmods/1956_beta#1874]
I feel bad for the guy, its like showing to your friends how you looked when you were 18. There is a more recognizable portrait of him when he was a bit older, I think before he got to be president. The one used here is quite ideal for the game: 

https://upload.wikimedia.org/wikipedia/commons/9/9c/General_Marcos_Evangelista_P%C3%A9rez_Jim%C3%A9nez%2C_Venezuela_Colorized.jpg

**Comment by TheBrit7** [comment]
He was 22 in 1936, the portrait picture he is based on is from 1941 when was 26. And the one you linked is most likely from the late forties-early fifties. I do get your point, but it's not very accurate for the time.

**Comment by hurafloyd** [comment]
> 
> 
> He was 22 in 1936, the portrait picture he is based on is from 1941 when was 26. And the one you linked is most likely from the late forties-early fifties. I do get your point, but it's not very accurate for the time.

I agree, thought it was worth a try x).
