### ISSUE TITLE
Venezuela Focus Tree: Visions up North

### ISSUE THREAD

**Issue by hurafloyd** [deliciousmods/1956_beta#1878]
I have some suggestions regarding this part:

1) The tree "Moderate the Cabinet" shouldnt have access to "Visions up North", since Visions up North is an expansionist (or even anti-communist if Fidel Castro comes to power in Cuba) ideology that doesnt go well with Angarita's ideology as set up in the mod.

2) Puerto Rico can also be added as a core with the "Strike the Giant" besides puppeting the USA, it will also make sense if the "Our Heritage" political action is followed.

3) (I havent got to this focus yet but with the description given I assumed this) By the historical timeline followed by the game, Trinidad and Tobago is being swapped between the UK and USA during the war, the focus of "Claim Trinidad" could generate conflict with either of the two since Trinidad and Tobago wasnt independent at the time. If the US is controlling the island then "Intervention in Brazil/Strike the Giant" would become useless as a focus since there will be a choice to declare war to the US beforehand.

4) Suggest changing "Secure Hispaniola" to "Secure La Española", to keep its original Spanish term.

5) "Unión del Caribe" should also have Jamaica as a core (Puerto Rico will be included in "Strike de Giant"), although Jamaica is under UK control, the "Claim in Trinidad" decision will be consistent with this focus.

**Comment by TheBrit7** [comment]
I have expanded on this path for the next update, most of the things you listed I have already done. Thanks for suggesting though,

**Comment by ilkober** [comment]
Good suggestion, but would you mind consolidating ALL of your 7 opened issues into big one please?

**Comment by TheBrit7** [comment]
> Good suggestion, but would you mind consolidating ALL of your 7 opened issues into big one please?

Yeah please do, it's much easier for me to read one big list rather than look at 10 different issues

**Comment by hurafloyd** [comment]
My bad, I thought it would be easier for you to classify issues with different entries to avoid mixing them and to let you establlish which ones to prioritize.

Whatever comes afterwards I will put it in a single list.
