### ISSUE TITLE
Another suggestion list for Venezuela and South America

### ISSUE THREAD

**Issue by hurafloyd** [deliciousmods/1956_beta#1880]
Generals/Admirals

- Gabriel París Cordillo (no idea which country, Colombia, Panama, Ecuador or Peru?), the picture of the general is overflowing from its boundaries.
- Luis Felipe Llovera Páez (Venezuela) could use its own picture, since there is one that can be found on the internet.
- Oscar Emilio Ghersy Gómez (Venezuela) could use its own picture, since there is one that can be found on the internet.

Venezuela Focus Tree

- Suggest changing "Establish the IFE" into a general focus that can be reached by developing either subtree.
- Suggest relocating "Expand Isla Refinery" into the "Gran Colombian Unification" tree (may be put the name if the island?).
- Suggest including a focus that improves Guyana's resource gain or add oil into "Gran Colombian Unification" tree.
- Suggest including a focus that improves the special forces amount by a percentage. Research benefits could also be included focused for paratroopers (Venezuela had a paratrooper brigade formed around 1950).

Colombia/Venezuela/Ecuador Focus Tree

- Suggest including a focus (or political action?) that demands the USA to give back the Panamá Canal as soon as the Bolivar Empire is founded.
- Suggest adding/modifying one of the focus related to the Gran Colombian Union to include extra recruitable population (may be the "Unify the Gran Colombia Army" focus?), when the Bolivar Empire is formed, it barely has any population to be worth its might with around 800k soldiers with 8.10% conscription (using The Greater Good, Extensive Conscription and Venezuela Paramilitarism) so having an extra % to recruit would be good. If the Hispanic Union is formed, may be instead of an increase of recruitable population, since I dont know if the recruitable population can be divided between countries conquered, may be an increase of core population in the Gran Colombia's focus tree.

Venezuela Events

- If Perez Jimenez is president, add an event (in 1950) that Carlos Delgado Chalbaud can be assasinated with both options bringing merits and demerits, may be like:
1) Assination: Perez Jimenez receives another quality that increases political power gain (Cold Blooded?), loss of stability, loss of a general, (if it comes in the update) loss of an advisor, 
2) No Assasination: stability gained, Carlos Delgado Chalbaud can become a military advisor, political power lost.

- If Angarita is president, allow an event in 1945 where a coup happens, may be in the form of a civil war. If lost the game ends and Romulo Betancourt comes to power.

Cuba Event

I wish some sort of resemblance can be added to Cuba's Fidel Castro revolution, he ousted Batista and won the revolution by 1958 so it might be too late, or can it be included?

Venezuela/Colombia/Ecuador vs. Brazil Event? Focus?

I was thinking if it was possible to add a political action were the Bolivar Empire demands Brazil to return some of the provinces within the Amazonia state and add it as a core, would be cool to have a South American "colonial" reference. May be instead of puppeting it? Actually, can certain provinces be given instead of the whole state? is it even possible? Or may be collude with Portugal to divide Brazil and retake the old territories for each country? I leave it to your consideration.

Focus could be: "Revoke the 1929 Treaty". Could gain conquer focus of the Amazonas state and add it as a core.
Focus could be: "Return to the Tordesillas Treaty". If Portugal agrees, Bolivar Empire and Portugal declare war on Brazil and divide the country (something like the partition of Poland with the Molotov-Ribbentrop pact) following the old Tordesillas Treaty demarcation of the New World.

Event could be: "Bolivar Empire demands northern Amazonas". If possible it can be all the provinces bordering Colombia, Venezuela and Ecuador instead of the whole Amazonas state.

_Historical reference: the old territory of the Viceroyalty of New Granada, colony of Spain, included lands that Brazil now has as its territory, which followed an old treaty supported by the Pope, called Treaty of Tordesillas which it literally drew a line on the New World to divide it between Spain and Portugal (the current borders were modified around the 19th century and ratified around 1929)._

**Comment by TheBrit7** [comment]
Thanks for another list. As for the generals, I have no real clue what causes the portrait to go out of bounds like that, I'll need to investigate further. And some generals and admirals have gotten their own portrait for the next update but our artists are busy people, it takes time.

**Comment by hurafloyd** [comment]
Brilliant! Its ok, I just share what I find to help you guys in case it hasnt been reported or noticed. I'll wait (im)patiently for the new update, I'll add more thoughts on how the game and focus tree feels on other areas in the following days.

Oh I just added something to the Gran Colombia's recruitable population idea, (if possible) it should only apply to the Gran Colombia core states (Venezuela, Guyana, Panamá, Colombia and Ecuador), it shouldnt carry over to the whole Hispanic Union when its formed (that would be too OP in my opinion).
