### ISSUE TITLE
 Fu Zuoyi 24/72 Army Division limit

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#19]
User Quote:

Bug: 24/72 Army Division limit
A general, Fu Zuoyi, appears to be capable of leading 72 divisions efficiently instead of 24. He possesses no related traits, and there is no visible reason why he should be capable of doing so. I gave him an additional 3 divisions to put him at 27, to see if it would auto-correct itself when the game logged him as having more than 24 - what SHOULD be his natural limit - bug there is no visual indicator that it isn't working as advertised. Will attempt to commit him to combat and see if it holds true.
Addendum 1: There is no visible penalty to his troops' combat modifier due to army limit excess. His limit appears to hold true, as advertised.

May apply to other generals and be related to the need to update generals.

**Comment by Greatexperiment** [comment]
Couldn't replicate the bug - but Fu Zuoyi is now properly assigned to Shanxi and has his art.
