### ISSUE TITLE
Japan Wargoal Question

### ISSUE THREAD

**Issue by cah11** [deliciousmods/1956_beta#1908]
When I was playing single player as the US, Briton, France and I all randomly got a puppet wargoal against Japan. I am playing with historical AI focus OFF and the Japan AI has chose the Democratic alternate history path, I took the Republican (but not fascist path) . Is this working as intended or is this a bug?

https://prnt.sc/1tafk7z - Screen cap of the puppet wargoal with the diplomacy screen open on Japan.

**Comment by TheBrit7** [comment]
Most likely that Japan left the naval treaty and both Britain and France sent them a warning, and if Japan refuses to cooperate they will get a puppet wargoal. This can apply to anyone in the naval treaties.
