### ISSUE TITLE
Venezuelan Oil 

### ISSUE THREAD

**Issue by zargona** [deliciousmods/1956_beta#1913]
Hi, when I select 
"Lift the oil curse" focus it doesn't remove national spirit "Venezuelan Oil"

![Screenshot 111](https://user-images.githubusercontent.com/18556743/135133113-a61cedc7-31bf-4d83-9c47-7c11aeaa6181.png)
![Screenshot 222](https://user-images.githubusercontent.com/18556743/135133120-ba4a4aab-8aa4-4d29-8e89-6b6ef6f99deb.png)

**Comment by TheBrit7** [comment]
We got it, fixed for next update
