### ISSUE TITLE
Destroyer 1936 "Lacks module" without MtG

### ISSUE THREAD

**Issue by YDum** [deliciousmods/1956_beta#1934]
I getting back to HoI4 with Rt56 after a while, and I am not able to build any 1936 destroyer since their "Design lacks one or more required modules:", with of course no module listed. Problem, I do not have the MtG DLC...

Strangely the 1922 design is ok...

HoI4 from Steam
Rt56 updated on 8 october from Steam
Active DLC: Death or Dishonor and Together for Victory (plus some cosmetics ones)
No other mods active

Of course I have restarted the game/try multiple nations (even ones with DD36 not researched at the start)/purge cache of the main game.

**Comment by Thinking-waffle** [comment]
Known and fixed.
