### ISSUE TITLE
Soviet Support Event

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#20]
User Quote:

There's an event that I didn't catch the ID on, it entails Soviet support for the war effort. It gives you the Support Equipment technology, the Type 24 & Stokes mortar technology and if I recall 2,500 rifles. Its worth noting that you already have both of those technologies on game start, so they don't need to be attached to the event. Potentially the event could give other technologies instead, but whether or not that's necessary is up to others.

**Comment by Greatexperiment** [comment]
The described event does not appear to exist. The closest one is a Soviet Support event for China that grants equipment but no tech.

**Comment by Zurich899** [comment]
Does anyone know which country this event is for? If not, we could probably close this issue and create a new issue if someone reports this again (ideally with more specifics)

**Comment by Greatexperiment** [comment]
I agree. Issue closed for now.
