### ISSUE TITLE
Vichy pull requests need to be resolved.

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#203]
This is an item for Waffle to deal with - just a reminder. I haven't touched it, as it so heavily deals with his own content.

**Comment by Thinking-waffle** [comment]
I have managed to make it work independently very recently so that's coming.

**Comment by Zurich899** [comment]
I just closed my pull request on this issue, since it looks like Waffles has this taken care of (don't want too many cooks in the kitchen).
