### ISSUE TITLE
Warlord Cliques should explain bonus system

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#21]
User quote:

 I think that it might have lower penalties the less there are, and they might go away entirely when you finish the last one off, but nothing in-game actually tells you this information. I left the mouse cursor on the National Idea title to see if the description would tell you, but it just gives you flavor text. I somewhat doubt that this is a bug, or that it isn't working as-intended, but something somewhere should tell the player how this works.

**Comment by Tyguy9112** [comment]
Closed

**Comment by Tyguy9112** [comment]
Reply, if you want reopened.
