### ISSUE TITLE
Unable to continue Dutch political branch

### ISSUE THREAD

**Issue by zwinout** [deliciousmods/1956_beta#2176]
The Dutch political branch seems to be broken and the focuses doesn't seem to be connected, which makes it impossible to continue after "Gateway to Europe" focus.
![Screenshot_20220403_224453](https://user-images.githubusercontent.com/26856815/161447863-533e936e-4ae8-4d38-bc04-ff00bc7be45e.png)

**Comment by ilkober** [comment]
Please read the tooltip and what it says.

**Comment by zwinout** [comment]
> Please read the tooltip and what it says.

What do you want me to read? It states that the prerequisite is to either have caved to the British or stay neutral, and as you can see in the previous focus, I have caved to the British.

**Comment by ilkober** [comment]
Did Britain change ideology in the meantime?

**Comment by marijn211** [comment]
If Britain is currently changing ideology it might not be possible to pick a focus at this time
