### ISSUE TITLE
France CTD

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#218]
Users are reporting CTDs involving France in 1938.

**Comment by bonoff26** [comment]
Not playing as France, but still get a CTD. From the error log: [16:25:59][persistent.cpp:42]: Error: "Malformed token: Cavalerie Motorisée, near line: 8
" in file: "history/units/WLL_motor_cavalry.txt" near line: 8
[error.log](https://github.com/deliciousmods/1956_beta/files/1977755/error.log)

**Comment by Greatexperiment** [comment]
I've been able to isolate one of the CTD issues down to something involving Japan and China. If either of these are cheat-annexed during their war, the crash can be averted. It's also worth noting that all files were systematically removed during testing to try and isolate the source - but it still crashed. Which suggests it's actually a file in vanilla causing the trouble.

**Comment by Zurich899** [comment]
New report from a player that might be relevant to this CTD.

outhalo1 1 hour ago 
playing as france, the germans demand the sudenland and i defend the czechs and then apr 24 the game crashes

**Comment by Greatexperiment** [comment]
Tested on another save - war with china happen, annexed china as per the previous fix and it still crashed anyway. So either this is a different CTD, it's the same one - and I have no idea anymore what the hell is going on.

**Comment by Greatexperiment** [comment]
I remember seeing several users push fixes for the Vichy issue and France in general, but they couldn't be accepted for various reasons. I'd like to see another attempt at that.
