### ISSUE TITLE
 Issue with the Burma Road

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#22]
User Quote:

The "Improve The Burma Road" focus has very specific and very odd requirements, due to this I have yet to either see the AI make use of it or have the chance to use it myself. I have finished multiple China campaigns to completion (well, I stop after I take over the mainland against Japan and annex the Soviet Union), and I have yet to see it as a feasible possibility. Now there is even a Decision for it, but it will most likely be just as unobtainable.

**Comment by Greatexperiment** [comment]
Decision removed as it is redundant with the focus, and also depended on having WTT.
