### ISSUE TITLE
Historical isn't historical (multiplayer)

### ISSUE THREAD

**Issue by tankirules** [deliciousmods/1956_beta#2236]
Playing with my friends on historical, twice, britain and USA have gone fascist, and inner mongolia has seceded from japan and the chinese soviets have declared on ma clique, which afaik doesn't happen in historical AI?

**Comment by marijn211** [comment]
Inner mongolia seceding was fixed, you almost certainly triggered some condition that makes US/UK cancel their historical AI, see the following: https://www.reddit.com/r/RoadTo56/comments/vqkxmo/comment/if06l3k/?utm_source=share&utm_medium=web2x&context=3
