### ISSUE TITLE
Brazilian Focus Tree Impassible

### ISSUE THREAD

**Issue by tkennedy3159** [deliciousmods/1956_beta#2238]
I tried playing as Brazil and got stuck on the focus tree where I could not go any further.

Getting some support for communism adds decisions, one of which allows you to convert the country to Communism once 50% support has been reached. I did this and the leader changed away form Getulio Vargas, but choosing an ideology in the focus tree (Communism) required that I had Vargas as a leader. Since I converted to Communism before reaching that point in the focus tree, I could not continue.

I suggest removing the requirement for Vargas as a leader. Love the mod thank you for all the hard work!

**Comment by ilkober** [comment]
Added a bypass in case he is no longer a leader for all those four focuses in case one transits earlier
