### ISSUE TITLE
Missing Honduras Leader Portraits

### ISSUE THREAD

**Issue by Zurich899** [deliciousmods/1956_beta#224]
Since no one had time to create leader portraits for Honduras, could someone please create them for the next release? If none of the artists have enough time, I could also just give them generic portraits.

Samuel Zemurray (Fascist) 
https://media.gettyimages.com/photos/portrait-of-russianborn-american-businessman-and-president-of-the-picture-id121718183

Manuel Calix Herrera (Communist)

http://4.bp.blogspot.com/-0WcJjpgWHmY/UmWF0nPfQxI/AAAAAAAADI8/_bgQT9S8NAQ/s1600/C%C3%A1lix-Herrera-mugshots-edited-small-file.jpg

Infante Juan (Non-Aligned) 

https://i.pinimg.com/originals/a0/69/ee/a069ee16262bfd499beaed28228c531d.jpg

Jaime (Non-Aligned, leads Honduras if Juan takes the Spanish throne)

https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Jaime_Enrique_de_Borb%C3%B3n.jpg/220px-Jaime_Enrique_de_Borb%C3%B3n.jpg

From the comments:

Napoleon III (Algau1) 14 hours ago 
For Honduras, when facist and chossing samuel zemurray as the facist leader, there's no leader portrait...PLEASE ADD ONE :)

Datguy47 10 hours ago 
Tested the communist honduras portrait, that doesnt work and neither does the event for the USSR to send you guns (I'll look into that second part)

Datguy47 10 hours ago 
No leader portrait for monarchist Honduras either...

**Comment by SpicyAlfredo** [comment]
Give them generic for now, well get a artist

**Comment by TheHistorian94** [comment]
I will be doing them

**Comment by Greatexperiment** [comment]
Did this get take care of?

**Comment by Zurich899** [comment]
I saw in one of the patch notes that this was added, and thank you for that. The portraits that I've seen look fantastic. The only thing missing was a portrait for Zemurray when he becomes a field marshal through the micro-management focus, but I think that can be made by resizing his current portrait.

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
