### ISSUE TITLE
CV Jet Fighters only have Air Superiority/ Interception missions

### ISSUE THREAD

**Issue by kmjohnsonpgh** [deliciousmods/1956_beta#2251]
As you can see below, CV Jet Fighters are shown to have the same missions as regular fighters/ jet fighters on the research page. However, when they are used to create an air wing, they are only able to perform the air superiority or interception mission. I believe they did have the correct missions available in the past at some point, so I figure this is a bug as opposed to an intended design change.

![Research Page](https://user-images.githubusercontent.com/105891846/169416119-9d29b9dc-4193-4d39-9013-328d41738112.jpg)
![Air Window](https://user-images.githubusercontent.com/105891846/169416120-01c0bef5-deae-4e18-9c13-6d096ca276cc.jpg)

**Comment by AbbusF** [comment]
![圖片](https://user-images.githubusercontent.com/50837019/171259835-aed5600d-4b95-47d9-b1ce-8671f923c171.png)
Thank you for your report, it will be fixed in the next patch.
