### ISSUE TITLE
Reported Honduras Issues

### ISSUE THREAD

**Issue by Zurich899** [deliciousmods/1956_beta#226]
I noticed that a few people posted issues that they were having with the Honduras integration. I'll start fixing them now and attached the pull requests to this issue. The reported issues are below:

- USA will intervene in Honduran wars (focuses already remove Monroe doctrine, but there is probably another flag for American intervention in R56 that needs to go away)
- Missing construction company icon
- Issues with the Soviet guns focus
- Missing leader portraits (covered in another issue, but I'll add generic ones for now)

If anyone notices any other issues with Honduras, please report them here and I'll look into them.

**Comment by Zurich899** [comment]
Alrighty, all known Honduras issues have been fixed. Please let me know if anyone finds any more issues and I'll fix them as soon as possible

**Comment by Zurich899** [comment]
I played Honduras again after a long hiatus, and made a list of the issues I saw. I'm going to start working on them tomorrow, but thought I would add the list now. If I've missed anything, please let me know and I'll look into it:

- Fascist Branch, change focuses for Central America to match commie and monarchist branches or reduce the chance of accepting. Only half or a quarter of the countries in Central America should accept annexation, not all of them.
- Add a decision to integrate Central American countries if the player declares war manually (No idea why people would do it, but I'll make them 100 PP each as an inefficiency tax)
- Replace the micromanagement focus description with a Zemurray quote 
- Rosario Mining Company, Lowell Yerrex, and light aircraft manufacturer icon disappeared (will look into this last, since I'm unsure of how to fix it)
- Correct the requirements for the communist Panama Focus, Costa Rica ownership is stated twice
- India coup focus text is too long, this focus should also be blocked block if India is in a civil war or fascist
- See if there's a way to delete leftover troops (possibly give USA and UK temporary military access after Belize / Panama events)
- Replace the banana republic upgrades (fascist path) with the new icon
- Banana Boat Mass Production Focus text needs to be fixed
- Change the "Doctrine Effort" to something else (Special Research Division, army focus techs)
- The decision to core Colombia and Ecuador needs to disappear after being taken, same with the Western US coring decision
- Give Honduras its proper banana yellow color after it becomes the Banana Empire (I think that got lost in the move, but I really liked that color)

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
