### ISSUE TITLE
The same broken, ahistorical events in every single game

### ISSUE THREAD

**Issue by ThereNoMoreGoodNames** [deliciousmods/1956_beta#2297]
So for whatever reason the same ahistorical events keep happening in every single game regardless if historical mode is on or not, if I use any of the custom country paths, if I use spectator mode, etc. Mengjiang always declares independence from Japan right after asking for their protection, I literally had to remove this event from the game files cus it was driving me insane. Also, Emilea Airheart always lives, and I'm not sure if this is related but Xinjiang always joins the Comintern.

**Comment by ilkober** [comment]
Please, play the most up-to-date version of the mod
The event for Mengjiang was removed on the latest patch and is no longer present.

I don't know how many games you tested, but the RNG on Earheart is actually 50-50:
	immediate = {
		random_list = {
			50 = { ENG = { news_event = { id = news.48 } } }
			50 = { ENG = { news_event = { id = news.49 } } }
		}
	}
So having played a big amount of games shall ensure that there is no bias to that
UNLESS
	trigger = {
		date > 1937.7.1
		NOT = { has_global_flag = earhart_disappeared}
		country_exists = USA
		USA = { has_war = no }
		NOT = { has_country_flag = amelia_active_ace }
	}
Never triggers, which for your ahistorical games might be the case

Xinjiang was tweaked in the coming update too, so please check that one again and report your findings please
