### ISSUE TITLE
Crash on launch (Directx 11)

### ISSUE THREAD

**Issue by tankirules** [deliciousmods/1956_beta#2354]
I have not played for a month, I just launched road to 56 (It seems like there is a new version because of new loading screen art?) and it crashes when launching. I have enclosed the error.log
(Note I have tried with both directx 11 and opengl)
[error.log](https://github.com/deliciousmods/1956_beta/files/9335989/error.log)
.

**Comment by ilkober** [comment]
If you are in our discord server, check pinned messages in #general 

Otherwise, make sure you only have r56 mod on.
