### ISSUE TITLE
CTD in Sudeten crisis event fix

### ISSUE THREAD

**Issue by LittleRedPoint** [deliciousmods/1956_beta#2388]
Error: Error: "Malformed token: Mobilizační Těleso, near line: 24" in file: "history/units/CZKE_mobilisation_formation.txt" near line: 24

It seems to be template letter name fix. at least after the fix the CTD did not occur.

\history\units\CZKE_mobilisation_formation.txt

Current template name:
division_template = {
	name = "Mobilizační těleso"	

Should be  (T instead on t)
division_template = {
	name = "Mobilizační Těleso"

**Comment by ilkober** [comment]
Thank you for the report!
I already have seen this occur in an error log and a few days ago changed loaded .oob to division spawn in states (effect from event basically)

Waffle-bba-3 branch shall contain the fix if you are interested to see if it was resolved
