### ISSUE TITLE
Devastator's Suggestions

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#240]
user quote:

your GER_names_divisions file in common\units\names_divisions doesnt work for the neutral style divisions properly for the neutral government type, it only unlocks those lists if you go democratic. 

Adding an OR argument for the focus requirement, like this 

OR = {
has_completed_focus = GER_a_new_reich
has_completed_focus = GER_restore_weimar
}

or simply removing the has_completed_focus would allow democracries and neutral governments to use the namelists

I realized that companies (specifically air in this case) weren't giving the bonuses to the newly added equipment (such as FIghter Bombers) 

After some digging I was able to fix the issue by moving 'r56e_traits.txt' from 'common\country_leader\replace' to 'common\country_leader' and renaming it to '00_r56e_traits.txt' 

id recommend checking any modded files youve added in a similar situation to this. (Vanilla file in same folder has enumeration whereas the modded one does not) 

Have a good day and I wish you guys luck on updating the mod!

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
