### ISSUE TITLE
Reichskommissariats don't control all provinces they suppose to get

### ISSUE THREAD

**Issue by IVENEND** [deliciousmods/1956_beta#2404]
Using decision to found **Reichskommissariat Ostland**, **Reichskommissariat Norwegen** and **Reichskommissariat Ukraine** don't make these three Reichskommissariats control all provinces they suppose to get: 

**screenshot:** https://i.imgur.com/eCcjO20.jpeg

**Reichskommissariat Ostland** doesn't have core on Lativia, Estonia, Lithuania's provinces which are newly added in NSB dlc.

**Comment by marijn211** [comment]
Mentioned as fixed in recent PR
