### ISSUE TITLE
Norwegian Communist Leader

### ISSUE THREAD

**Issue by TheHistorian94** [deliciousmods/1956_beta#241]
Here Egede Nissen's portrait: 

![nissen](https://user-images.githubusercontent.com/39300456/40177133-f311f318-59dd-11e8-82d1-61668ddd9716.png)

**Comment by Plutozz** [comment]
Something I'll fix during my Nordic/Scandinavian overhaul.
Did you make this portrait? If so, I'll use it.

**Comment by TheHistorian94** [comment]
@Plutozz , here an improved version for you 
![edge nissen improved](https://user-images.githubusercontent.com/39300456/40581445-badbd4a0-6158-11e8-9872-7e354d8417ee.png)

**Comment by Plutozz** [comment]
Awesome!

**Comment by Greatexperiment** [comment]
Have these been used? Can the issues be closed?

**Comment by Plutozz** [comment]
Not in the mod at the moment - but it is in the Nordic Overhaul I'm working on currently so it will be added through that eventually.

**Comment by Greatexperiment** [comment]
There are a number of these portrait related issues open now - and I would like to close them.

**Comment by Plutozz** [comment]
I could throw these in now if you want me to.

**Comment by Greatexperiment** [comment]
Sure, that would be great. So long as you have the files from all of them and they can be closed?
