### ISSUE TITLE
Can not choose proper icon when designing tanks

### ISSUE THREAD

**Issue by IVENEND** [deliciousmods/1956_beta#2411]
Please notice this issue happens on **all German** tank chassis, and **probably** also happens on tank chassis of other countries. The report below is just an example.

The default icon, which appear on techtree interface, of Advanced Medium Tank chasis is this:
**sreenshot**: https://cdn.discordapp.com/attachments/338700374389030912/1038785598955192380/image.png

However, when I design a tank with this chasis, I can not choose this icon in Tank Designer interface. This problem will appear after player press the "save" button in Tank Designer interface.
**sreenshot**: https://cdn.discordapp.com/attachments/338700374389030912/1038785783080943686/image.png

----------------

Also, not a bug but a suggestion. The default icon of tank chassis are probably from the mod "Lamp's Eqpt Icons" (https://steamcommunity.com/sharedfiles/filedetails/?id=947459516). Now "Lamp's Eqpt Icons" added a couple of new alternate tank icons for each type of tanks. 56 can also add them if you want.

**Comment by AbbusF** [comment]
A extremely long wait but it is finally solved in August 2023.
