### ISSUE TITLE
Forming Regional Defense Council of Iberia as Anarchist Spain

### ISSUE THREAD

**Issue by ghost** [deliciousmods/1956_beta#2525]
![image](https://user-images.githubusercontent.com/43446551/219963293-6868449c-05fe-49bd-9db2-faf1d9f98bfc.png)
![image](https://user-images.githubusercontent.com/43446551/219963316-84d36264-36a5-4eed-948e-635e26d23a07.png)

I noticed that after finishing the focus "Portuguese Anarchism" and helping Anarchist Portugal defeat the Portuguese government, Anarchist Spain doesn't automatically annex Anarchist Portugal after peace deal, hence causing the following national focus "Regional Defense Council of Iberia" extremely hard to complete.

My suggestion is:
1. add an event to automatically annex Anarchist Portugal after peace deal;
or
2. adjust the effect and prerequisite of national focus "Regional Defense Council of Iberia" `id = SPR_regional_defense_council_of_iberia.`

**Comment by marijn211** [comment]
The focus condition, focus icon and effects do not match R56, I strongly suspect this is not a R56 issue
