### ISSUE TITLE
Several errors involving popularities not adding up to 100 in BEL_additional_events.txt

### ISSUE THREAD

**Issue by Tcw7468** [deliciousmods/1956_beta#2528]
The game is crashing sometimes for me, and the error log usually has an error involving popularities not adding up to 100 in this file. It looks like several of the set_popularities fields don't add up to 1. Based on how the numbers add up it looks like the error was caused by someone bulk adding "0." in front of integers, not accounting for the fact that for instance 1 should be .01 and not .1.

**Comment by marijn211** [comment]
I think the crash is from another issue in the same file, both fixed already however
