### ISSUE TITLE
Germany should probably be nerfed and the number of focuses reduced to keep their annexations on time

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#253]
https://i.redd.it/k944cecrdiz01.png

"so in summary :

166 mill

231 civ

28 naval

39% research bonus

4.29PP since 1937 (and 1400pp that i cant even use)

CAS3, FTR3

50% research bonus for FTR4

full land doctrine

CA3, SS3, CL3 navy

I know I min-maxed a bit and took over Romania and Yugoslavia (by accident) but this is plainly broken for a 1940 nation, most of my tech is 1944 era and I haven't even finished half the focus tree..."

**Comment by Thinking-waffle** [comment]
"Germany gets A LOT of PP both via its 2 silent workhorse advisors and its +25% base, on top it gets 3x35 day +120pp focuses that also give extra stuff and 75pp for Anschluss ect... effectively it gets all its advisors and national spirits on day 1 while other nations usually don’t have a full set till late game (probably largest source of snowball, 600pp in May 1936)

It has very large research bonuses for its aircraft tech and land doctrine tree, if you actually try for it you can get jet fighter techs in 1941 with the 50% off bonuses

It has a lot of 35 day focuses in general, and they aren’t “minor” ones that just give some relationship or army XP but major economic or military focuses, it feels like someone structured the tree so that you could take everything at the same time rather then pick and choose your path

That brings me to the other point, it lacks choices, you can prepare for war with every, take all the economics, and then do the whole political sphere tree without ever going to war or making a “do I want A or B” choices

No MEFO or anything to drain PP or really threaten Germany’s expansion and growth

Things I like :

Volksgemeinschaft and Two sided economics really are “give and take” focuses where you exchange something for another

The political sphere trees, they are actually really nice, give good bonuses, and take an appropriate amount of time to do

Multi stage annex goal focuses

Locked research slots (after playing it a few times this makes very real sense)

Suggestions :

Lock the Anschluss, Sudetenland and lebensraum focuses behind denounce Versailles and its alternates (just make requires X national spirit criteria)

Half the research bonuses

Stretch out the 35 day focuses, or reduce their impact (for example issue with steel mills and appoint Economics bother give very large permanent bonuses more fit to a 70 day focus)

Give more choices either through focus length one or the other type choices (the research bonuses in particular could do with some of this)"

**Comment by SpicyAlfredo** [comment]
The whole tree is honestly problematic in it's current state. I can go though it tomorrow and make number adjustments and test.

**Comment by Plutozz** [comment]
The mod that it's based off has also been updated quite a lot. If that's anything to add.

**Comment by Greatexperiment** [comment]
There are more nuanced ways to keep the focuses "on time" than removing them. 

MEFO bills should be implemented, and actually have been 'mostly' as there are a ton of script and event references that have to be added throughout the game to make it work as intended. I've put in a lot of them, but probably missed quite a bit. As an experiment we could re-enable the MEFO decisions and starting ideas to see how well it works in its current state.

While the original mod may have been updated, there have been such a large number of edits to the tree that we'd risk backtracking pretty heavily. As with the case in other trees, it's much better to continue down our own path than try to bolt on whatever updates may have come down the line. Updating from their base would be similar to trying to merge in a branch on git that was created months ago. It wouldn't be pretty.

**Comment by Greatexperiment** [comment]
Also, really, this is all academic. We have rampant CTDs that haven't yet been solved - and that really should be the #1 priority. Doing a major overhaul on a tree that most users actually like, instead of solving the very real and immediate issue of crashes to desktop - seems a bit odd?

For reference sake and a reminder, there are at least two crashes left out of four. Something to do with China / Japan and the base game files, and something to do with France and the spawning of Vichy / FF.

**Comment by SpicyAlfredo** [comment]
It's not a overhaul just number adjustment atm. Also I can go haunt down the CTD's though it will shelf my projects for the time being.

**Comment by SpicyAlfredo** [comment]
Honesty the China/Japan CTD's might have to involve a overhaul...

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
