### ISSUE TITLE
Ger_1936 Squadrons missing and Squadron names in english bug

### ISSUE THREAD

**Issue by unknownaussie** [deliciousmods/1956_beta#255]
so the issue is the german squadron names are in english and after looking on win merge there are squadrons missing from the modded ger_1936 file but i have no clue why the squadron names are in English i unselected road to 56 and tried each of the mods individually and it is something in the expanded tech mod thats doing it

**Comment by Thinking-waffle** [comment]
That's useful info

**Comment by unknownaussie** [comment]
ik the luftwaffa squadrons missing can be replaced easy i looked up both ger1936 files in winmerge

**Comment by Tyguy9112** [comment]
Reply, if you want reopened

**Comment by unknownaussie** [comment]
What the problem is still not fixed?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tyguy9112** [comment]
I'll check into that problem, I'm reopening your case.

**Comment by unknownaussie** [comment]
So basically all the german squadron names are the default names like fighter squadron 1 ect ect and the liftwaffe is missing like 4 squadrons at the start of the game i thought it would be fixed because at the time i went and found the source of the problem and went on diacord and showed one of the lead guys

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tyguy9112** [comment]
Alright, thank you for the information, I'll check into it.

**Comment by Tyguy9112** [comment]
This bug was fixed in an update, I do not when it was fixed, but I had my bug checkers check the game, and no bug was found

**Comment by unknownaussie** [comment]
so all the german squadrons are there correct names as in jadgeshwader 2 ect ect and the correct ammount of squadrons are there?

**Comment by Tyguy9112** [comment]
Yes, it should be now. If it's not please take a screenshot of what you are saying, that provides more detail so we can reproduce it.

**Comment by unknownaussie** [comment]
its been partially fixed when you make new squadrons they are still the generic name and there is still squadrons missing

**Comment by Tyguy9112** [comment]
What squadrons are missing?

**Comment by unknownaussie** [comment]
never mind the squadrons are ther esorry but yeah its just the name thing but thats minor

**Comment by unknownaussie** [comment]
hey tyler is it ok to add a new bug report here all the aircraft icons in the australian tech tree are all wrong you could copy the ones from the uk or us tree or use the original game ones

**Comment by unknownaussie** [comment]
ok cool so yeah the icons for some of the australian tanks and planes are wrong for example the skua is a stuka and some of the planes are the wrong aircarft or there just invisible i can help if ud like
