### ISSUE TITLE
What is the current plan for countries with two focus trees?

### ISSUE THREAD

**Issue by Cantthinkofagoodname** [deliciousmods/1956_beta#2552]
Will they both be developed or one has higher priority?
I want to update and add some focus tree that are missing new focuses added by the vanilla patches,  but I am not sure whether I should work on the standard one or the R56 one. For example, Australia has new focuses currently in the vanilla update but not included in the R56 std tree.

If the standard/vanilla trees are focused, is it okay to expand those trees by adding focuses that are from r56?

**Comment by marijn211** [comment]
the added focuses should be added, unless we have similar replacement content, like, no need to add vanilla's 2 new fascist focuses when we have a branch dedicated to the same topic
Please check the discord for more information
