### ISSUE TITLE
Chilean Communist Leader portrait, Carlos Contreras Labarca

### ISSUE THREAD

**Issue by TheHistorian94** [deliciousmods/1956_beta#256]
Hi guys, I think my skills have now improved. Here the chilean communist leader's portrait. Feel free to use it, provided you credit me.

![carlos contrera labarca for hoi4](https://user-images.githubusercontent.com/39300456/40569457-0c438310-6082-11e8-8f42-03b83e943903.jpg)

**Comment by Thinking-waffle** [comment]
you should use the standard leader background

**Comment by TheHistorian94** [comment]
I am using this: 

![hoi4 background portrait](https://user-images.githubusercontent.com/39300456/40570120-d1511834-6087-11e8-9332-e93d743aa9d4.jpg)

Do you have a better one?

**Comment by Thinking-waffle** [comment]
https://imgur.com/g7qdi1W

**Comment by TheHistorian94** [comment]
Thanks Thinking-waffle, I had found that alrady by myself while you were posting 💃 

Here it is: 

![carlos contrera labarca definitive](https://user-images.githubusercontent.com/39300456/40570267-366819b0-6089-11e8-93a0-d4b76cd88562.png)
