### ISSUE TITLE
! Most Wanted ! Cuban Communist Leader Blas Roca Caldeiro Portrait

### ISSUE THREAD

**Issue by TheHistorian94** [deliciousmods/1956_beta#258]
I suggest in the next update to give Cuba his real communist leader, Blas Roca Caldeiro, for which I have realised this portrait.
![blas roca caldeiro hoi4](https://user-images.githubusercontent.com/39300456/40577373-e9d77ea2-6104-11e8-83fb-3d772f67d41b.png)

**Comment by Thinking-waffle** [comment]
isn't he a bit too yellow
he looks like Tintin's japanese
http://bullesdejapon.fr/wp-content/uploads/2011/11/tintin-Mandchourie.jpg

**Comment by TheHistorian94** [comment]
You are right, here the improved version. Feedback is always appreciated. 

![blas roca caldeiro hoi4](https://user-images.githubusercontent.com/39300456/40578267-33e5fdbe-6111-11e8-9c8b-fbaddf43ed9d.png)

**Comment by TheHistorian94** [comment]
Yeah, it was too fair. I have tried to improve it. Feedback is always welcome: 

![blas roca caldeiro hoi4](https://user-images.githubusercontent.com/39300456/40578369-45ce0cf4-6113-11e8-9242-564eaa6838dc.png)

**Comment by TheHistorian94** [comment]
I think this is gonna be definitive: 

![blas roca caldeiro hoi4](https://user-images.githubusercontent.com/39300456/40581336-0eb2382e-6156-11e8-9816-bfb8d52f1951.png)
