### ISSUE TITLE
Missing Portraits

### ISSUE THREAD

**Issue by TheHistorian94** [deliciousmods/1956_beta#261]
Since I am planning to work on each missing portrait in the game (at least the most important ones) I am opening a specific topic dedicated to it. The topic will be made of my contributions. 

Decent portraits painted by now: 

Edge Nissen, Norwegian Communist Leader
![edge nissen improved](https://user-images.githubusercontent.com/39300456/40592202-c9b2b876-621c-11e8-9c33-8bd009f396e1.png)

Obando Sanchez, Guatemala Communist Leader
![obando sanchez definitive](https://user-images.githubusercontent.com/39300456/40592207-dc746630-621c-11e8-8309-355a9b2ce4a1.png)

Blas Roca Caldeiro, Cuba Communist Leader
![blas roca caldeiro hoi4](https://user-images.githubusercontent.com/39300456/40592213-ea9a40fe-621c-11e8-96e0-ab80d75be1ef.png)

Andres Roxas Soriano, Philippines Fascist Leader
![philippines fascist leader](https://user-images.githubusercontent.com/39300456/40592225-016b15ce-621d-11e8-9110-575789d7c545.png)

Carlos Contrera Labarca, Chile Communist Leader

![carlos contrera labarca definitive](https://user-images.githubusercontent.com/39300456/40592245-3137d742-621d-11e8-87b4-c5579d33636a.png)

And a new one, Dai Li, Chinese Republic Fascist Leader

![dai li for hoi4](https://user-images.githubusercontent.com/39300456/40592300-bae2d320-621d-11e8-831b-a20279a6fd88.png)

More on their way.

**Comment by TheHistorian94** [comment]
New Addition: Daoud Khan, Afghani Democratic Leader (conservative)

![daoud khan for hoi4 afghani democratic leader](https://user-images.githubusercontent.com/39300456/40618906-4b46f016-6293-11e8-8f74-60a59d322d2d.png)

**Comment by TheHistorian94** [comment]
An addition I am really proud of. Axel Pehrsson-Bramstorp, Swedish neutral leader. @Plutozz , check it out for your Scandinavian overhaul. 

![axel pehrsson-bramstorp for hoi4](https://user-images.githubusercontent.com/39300456/40629698-75dbd6a4-62cd-11e8-9d86-82fa9a54c851.png)

**Comment by TheHistorian94** [comment]
A must have of every mod, Liberia's FACELESS NO MORE: Edwin Barclay's portrait @Thinking-waffle 
![edwin barclay for hoi4](https://user-images.githubusercontent.com/39300456/40670566-ea36272e-6369-11e8-8d44-1104ebda52a2.png)

**Comment by TheHistorian94** [comment]
Eudocio Ravinez, Peruvian Communist Leader

![ravinez for hoi4](https://user-images.githubusercontent.com/39300456/40681672-1211c026-638a-11e8-94d1-84b19454734e.png)

**Comment by TheHistorian94** [comment]
Please find Eusebio Ayala, Paraguay's democratic leader

![eusebio ayala for hoi4](https://user-images.githubusercontent.com/39300456/40747797-af358aca-645e-11e8-860b-b347dc9ad236.png)

**Comment by TheHistorian94** [comment]
An important add, Fritz Platten, Swiss Communist Leader: 

![fritz platten for hoi4](https://user-images.githubusercontent.com/39300456/40799432-db106fc0-650d-11e8-9b07-7923ad3a6f56.png)

**Comment by TheHistorian94** [comment]
Gustavo Ross, Chile democratic leader (liberal)

![gustavo ross for hoi4](https://user-images.githubusercontent.com/39300456/40911794-114058f0-67f0-11e8-93ef-bcfb740193c8.png)

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
