### ISSUE TITLE
Italian Communist Leader Proposals

### ISSUE THREAD

**Issue by TheHistorian94** [deliciousmods/1956_beta#262]
Italy has still a generic communist leader, which I think is something that must be fixed asap. 

Two options are available, in my opinion: the first one is Palmiro Togliatti. There is a problem with Togliatti though. He was not the official Secretary of the Italian Communist Party (Partito Comunista d'Italia) in 1936. However, lest be no doubts, he was surely the most influent member of the party abroad, and a pro-Moscow one. I think he should be the communist leader in case communism takes over in Italy at first, and keep his post if one opts for join comintern. The second option is Ruggero Grieco, general secretary of the PCd' I from 1934 to 1938. Grieco, as extensively shown by his son in a book called ' Un partito non stalinista' ( 'A non-Stalinist Party') pursued during his term an anti-Stalinist policy within his own party. This eventually led to his removal from any relevant office. In case one chose Italy's own path, as an alternative to Join the Comintern, I strongly advise he should become the leader. 

Let me know your views on the matter.

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
