### ISSUE TITLE
Chinese Crash

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#265]
user quote:

What I did get was a crash because one of the Chinese countries wanted to start a civil war but the game tried created two nations with the same country ID.

**Comment by Greatexperiment** [comment]
Also, multiple users report that going at the slowest speed will bypass some crashes. Also also, forming Vichy still causes crashes.

**Comment by Thinking-waffle** [comment]
it doesn't for me but I guess that it can overload some cpus
Time to use transfer equipment properly

**Comment by Greatexperiment** [comment]
I think perhaps that the vanilla files from WTT are spawning and event that uses a tag 56 also uses. So when they fire (one after the other) they make it crash.

**Comment by SpicyAlfredo** [comment]
This is correct in my testing. My own build had all the KMT Japan events gutted and I can avoid the crashes related to China. Also the mod we yse with China cannot run with WTT on

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
