### ISSUE TITLE
Soviet tank icons unavailable in the game despite being available in the files 

### ISSUE THREAD

**Issue by WesternFailMox** [deliciousmods/1956_beta#2665]
I don't know when this started, perhaps with NSB, but I started to notice that the Soviet Superheavy tank simply does not have an appropriate icon once you research and select it, the available icons are all generic superheavy tank icons, or superheavies from other nations, notably France and Germany.

This puzzled me greatly, and even more so went I delved into the files, from the "gfx" folder into the "equipmentdesigner" folder, and then the "tank" folder, where I found a large selection of Soviet tank icons that are simply not available in RT56, including the missing Soviet Superheavy tank icons. 

From what I understood of the code I found in the files, most of these icons are simply not mentioned at all in the code, hence why they do not appear in the game. Is this a bug? Or is it an intentional design choice? Will it be fixed? I do not understand why so many assets would just be left unused when there doesn't seem to be a clear reason for it.

I have only looked at the Soviets so far, and I am not sure if other nations suffers from the same issue.

**Comment by AbbusF** [comment]
Solved, it would be in the patch of August 2023.
