### ISSUE TITLE
Whatever this mess is

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#268]
User quote:

Ugh alright this is quite anoying... For some reason there is no longer a flag for nations to puppet non existing country's. It crashes the game quite often. For example germany conquering france without the help of italy, but another faction (Switserland, Free States) holds southern france... Germany wants to create Vichy France, game crashes because germany does not own souther france. France goes facists, gets the event to annex the benelux however germany is already ocupying luxembourgh, game crashes. Yugoslave is at war with bulgaria, Romania puppets bulgaria, game crashes.

Also on the China issue, provisional goverment of china and reorganized goverment of china don't combine into reorganized natiolist china. However reorganized natiolist china does get made by japans focuses and there will be a civil war. Mostly I see the new reorganized natiolist china get the tag D01 because it happens after the spannish civil war. However whenever I try to tag D01 when Japan lets it take the remainder of China it does not revert bag to the CHI tag, it keeps the D01 accoring to tdebug but if I try to tag it it won't let me because CHI does not hold any provinces.

**Comment by Greatexperiment** [comment]
It's doubly relevant because it seems to apply broadly to all the crashes we've been experiencing.

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
