### ISSUE TITLE
.Mod file

### ISSUE THREAD

**Issue by duyinthanhhoa** [deliciousmods/1956_beta#2693]
You guy only replace "history" but nothing else????

**Comment by marijn2112** [comment]
replace_path="history/states"
replace_path="map/strategicregions"

These are overriden completely, other (map) elements have the same filenames as vanilla so don't need this entry that disables the loading of the vanilla equivalent

**Comment by duyinthanhhoa** [comment]
> replace_path="history/states" replace_path="map/strategicregions"
> 
> These are overriden completely, other (map) elements have the same filenames as vanilla so don't need this entry that disables the loading of the vanilla equivalent

I can't play road to 56 so I asked this question. In other mod, they replace_path many thing else, not only "history/states" and ""map/strategicregions"
Like this kaiserreich .mod file 
`name = "Kaiserreich"
path = "mod/Kaiserreich/"

tags = {
	"Alternative History"
	"Events"
	"National Focuses"
	"Gameplay"
}
picture = "KR.jpg"
version = "0.25.4"


replace_path = "common/abilities"
replace_path = "common/ai_areas"
replace_path = "common/ai_equipment"
replace_path = "common/ai_focuses"
replace_path = "common/ai_strategy"
replace_path = "common/ai_strategy_plans"
replace_path = "common/ai_templates"
replace_path = "common/autonomous_states"
replace_path = "common/bookmarks"
replace_path = "common/bop"
replace_path = "common/characters"
replace_path = "common/continuous_focus"
replace_path = "common/countries"
replace_path = "common/country_leader"
replace_path = "common/country_tag_aliases"
replace_path = "common/country_tags"
replace_path = "common/decisions"
replace_path = "common/decisions/categories"
replace_path = "common/difficulty_settings"
replace_path = "common/dynamic_modifiers"
replace_path = "common/game_rules"
replace_path = "common/idea_tags"
replace_path = "common/ideas"
replace_path = "common/ideologies"
replace_path = "common/modifiers"
replace_path = "common/modifier_definitions"
replace_path = "common/names"
replace_path = "common/national_focus"
replace_path = "common/on_actions"
replace_path = "common/operations"
replace_path = "common/opinion_modifiers"
replace_path = "common/peace_conference/ai_peace"
replace_path = "common/peace_conference/categories"
replace_path = "common/peace_conference/cost_modifiers"
replace_path = "common/scripted_diplomatic_actions"
replace_path = "common/scripted_effects"
replace_path = "common/scripted_guis"
replace_path = "common/scripted_localisation"
replace_path = "common/scripted_triggers"
replace_path = "common/state_category"
replace_path = "common/technologies"
replace_path = "common/technology_sharing"
replace_path = "common/technology_tags"

replace_path = "common/units/codenames_operatives"
replace_path = "common/units/names"
replace_path = "common/units/names_divisions"
replace_path = "common/units/names_railway_guns"
replace_path = "common/units/names_ships"

replace_path = "events"

replace_path = "gfx/loadingscreens"
replace_path = "gfx/flags"

replace_path = "history/countries"
replace_path = "history/general"
replace_path = "history/states"
replace_path = "history/units"

replace_path = "map/strategicregions"
replace_path = "map/supplyareas"

replace_path = "portraits"

replace_path = "tests"
supported_version = "1.12.14"
remote_file_id = "1521695605"`
or Thousand week reich .mod file
`name="Thousand Week Reich"
path="mod/2204739234/"
tags={
	"Alternative History"
	"National Focuses"
	"Events"
	"Map"
}
version="0.3"
picture="thumbnail.png"
replace_path="events"
replace_path="common/abilities"
replace_path="common/ai_focuses"
replace_path="common/ai_equipment"
replace_path="common/ai_strategy_plans"
replace_path="common/ai_templates"
replace_path="common/characters"
replace_path="common/national_focus"
replace_path="common/ideologies"
replace_path="common/on_actions"
replace_path="common/scripted_effects"
replace_path="common/scripted_localisation"
replace_path="history/states"
replace_path="history/units"
replace_path="history/countries"
replace_path="common/autonomous_states"
replace_path="common/countries"
replace_path="common/ideas"
replace_path="common/scripted_triggers"
replace_path="common/technologies"
replace_path="common/bookmarks"
replace_path="common/units"
replace_path="common/units/equipment"
replace_path="common/units/names_divisions"
replace_path="common/unit_leader"
replace_path="common/wargoals"
replace_path="map/strategicregions"
replace_path="map/supplyareas"
replace_path="gfx/loadingscreens"
replace_path="map/supplyareas"
replace_path="common/decisions"
replace_path="common/decisions/categories"
replace_path="common/bookmarks"
replace_path="common/country_tags"
replace_path="common/ai_strategy"
replace_path="common/unit_medals"
replace_path="common/bop"
replace_path="common/peace_conference/ai_peace"
replace_path="common/peace_conference/categories"
replace_path="common/peace_conference/cost_modifiers"
replace_path="common/dynamic_modifiers"
replace_path="portraits"
supported_version="1.12.*"
remote_file_id="2204739234"`
these mod work perfectly fine, rt56 mod file have many subfolder like common,history,etc.
but you guy only do this
`version="1.12.*"
tags={
	"Beta"
}
name="The Road to 56 [Beta]"
remote_file_id="1088963694"
replace_path="history/states"
replace_path="map/strategicregions"`

**Comment by marijn2112** [comment]
We use the override vanilla by using the same filenames, there no need for more replace_path 's

**Comment by duyinthanhhoa** [comment]
but I using crack hoi4
