### ISSUE TITLE
Many files do not have AI implemented properly or consistently

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#27]
This is an old issue, due to the fact that many mod authors did not add AI or did it poorly. At some point it needs to be systematically updated:

1. With standard 4/1 values - with historical options being four times as likely as ahistorical ones.
2. Making sure the historical trigger check is present for all relevant focuses and events
3. Using the Sanity triggers for warmaking focuses and events

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
