### ISSUE TITLE
Colombia Focus "War with the Andeans" Always Triggers Bypass

### ISSUE THREAD

**Issue by OkaMoez** [deliciousmods/1956_beta#2700]
Focus requires you to own a subset of the same provinces that trigger the bypass, meaning the focus is always bypassed before it is available.

**Comment by OkaMoez** [comment]
Sorry for the formatting.
All this is from `...\common\national_focus\colombia.txt` starting at line 2059 for `COL_war_with_andeans`.

Prerequisites contains the following:
`controls_state = 306 #bogota`
`controls_state = 305 #ecuador`
`controls_state = 304 #panama`
`controls_state = 937 #north panama`
`controls_state = 307 #venezuela`

While the bypass is as follows:
`bypass ={`
`	306 = {`
`		OR = {`
`			is_controlled_by_ROOT_or_subject = yes`
`			is_controlled_by_ROOT_or_ally = yes`
`		}`
`	}`
`	305 = {`
`		OR = {`
`			is_controlled_by_ROOT_or_subject = yes`
`			is_controlled_by_ROOT_or_ally = yes`
`		}`
`	}`
`	306 = {`
`		OR = {`
`			is_controlled_by_ROOT_or_subject = yes`
`			is_controlled_by_ROOT_or_ally = yes`
`		}`
`	}`
`	307 = {`
`		OR = {`
`			is_controlled_by_ROOT_or_subject = yes`
`			is_controlled_by_ROOT_or_ally = yes`
`		}`
`	}`
`	937 = {`
`		OR = {`
`			is_controlled_by_ROOT_or_subject = yes`
`			is_controlled_by_ROOT_or_ally = yes`
`		}`
`	}`
`}`

It grants claims on provinces that I believe would be the correct ones for the bypass:
`add_state_claim = 490  #pastaza`
`add_state_claim = 491  #loreto`	
`add_state_claim = 303  #lima`
`add_state_claim = 494`
`add_state_claim = 492`

**Comment by TheycallmeBrick** [comment]
Should be fixed now in this or the next update - thanks for writing in.
