### ISSUE TITLE
The desert infantry lacks desert bonuses.

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#271]

**Comment by Greatexperiment** [comment]
This is covered in another issue already on the system, and has been a long standing one. For whatever reason Desert, and one other terrain type, don't load a visual in the tech description to show their bonus. This is a vanilla-side issue. The code itself is fine and in line with all the other terrain type bonuses.

**Comment by Thinking-waffle** [comment]
Couldn't we put a tooltip to reassure people that it does work?

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
