### ISSUE TITLE
AI seems to rush SRD research in early game while ignoring the basics

### ISSUE THREAD

**Issue by mjholub** [deliciousmods/1956_beta#2776]
I've only played r56 for a little while but I've noticed, either when switching to other nations via console commands or just when I was unable to construct things like radar stations at almost any of my allies' territories without doing the faction research continuous focus (even around 1940 and when I had over a dozen of them).
This is because the vanilla research, especially things like the techs that give industrial/research buffs get kinda neglected by the AI, while there are often more than a half of their research slots going to S.R.D., which, if I understand this correctly, is meant to be rather used in the late game. 

Therefore I think there should be some (ahead of time I guess?) penalty in place that would decrease once the real essentials get researched, that would somewhat deter especially the nations with less research slots, from rushing SRD before covering the basics. Iirc some nations didn't have Electronic mechanical engineering while at least 2 techs from the SRD section were already researched.

**Comment by SpicyAlfredo** [comment]
Fixed in upcoming hotfix

**Comment by mjholub** [comment]
A small update now that 1.14 was released which rebalanced research priorities: might want to ensure the fix still works and also to possibly refactor research weighing logic with the new AI strategy `research_weight_factor`.
