### ISSUE TITLE
The expanded techs strangely create a conflict with the names of the German air squadrons

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#280]

**Comment by SpicyAlfredo** [comment]
That's a new one. 

In what way do they conflict?

**Comment by Thinking-waffle** [comment]
I don't know unknownaussie did the tests
and narrowed it to that mod

**Comment by Thinking-waffle** [comment]
He reported the bug a month ago

**Comment by SpicyAlfredo** [comment]
I recently updated the oob of Germany airwinngs in this build. Ill test to see if they still conflict

**Comment by Greatexperiment** [comment]
Good to know if this is still the case?

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
