### ISSUE TITLE
TWAS Equipment Bugs

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#282]
Resolve cascading TWAS-related bugs, due to needing to either integrate or fully remove the expanded upgrades part of the mod.

**Comment by SpicyAlfredo** [comment]
Just need to edit the vaule of the upgrades where very they are...

**Comment by Greatexperiment** [comment]
Yeah, among other things. If you feel like handling it, okay - but otherwise I'll spend some time on it today. Especially if you already figured out the China crash.

**Comment by Greatexperiment** [comment]
The bug wasn't what I originally thought it was, and needs further investigation.

**Comment by PordyHUN** [comment]
I think we can close this issue due 1.6 completely renew the TWAS equipments.
