### ISSUE TITLE
Ship Balance

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#286]
User quote:

The US (And I believe the UK and Japan) currently gets varients of its ships created automatically. This isn't the worst idea, as it helps generate historical types. Unfortunatly they are entirely overpowered versus any of the vanilla ships. I current have an Essex Class that travels at the break neck speed of 48 knots. Who ever made this change disregarded balance, as the ships are upgarded past the regular maximum (even in Road to 56). The naval elements are currently broken enough as is, this doesn't help. It would be nice to see this balanced.

**Comment by Tyguy9112** [comment]
Reply, if issue reoccurs.
