### ISSUE TITLE
Korea focus crash

### ISSUE THREAD

**Issue by Altitud49** [deliciousmods/1956_beta#2885]
![image](https://github.com/deliciousmods/1956_beta/assets/89410004/a91f6cf2-4f64-4939-a074-b6126e025964)
Game likes to cry very loud about some overlord error which might crashes the game when Korea begins this focus with no overlord. 
![image](https://github.com/deliciousmods/1956_beta/assets/89410004/1594253a-2453-4d30-9555-c1e9d71034fb)
Edit: the game crashed even with a temporary fix so might also be denmark 
![image](https://github.com/deliciousmods/1956_beta/assets/89410004/e9cbf027-e28f-4292-8efe-796d518f0dac)

**Comment by Thinking-waffle** [comment]
I think that it's because it checks for the overlord but not if it's a puppet first and so the overlord doesn't exist and the game freaks out. Well done.

**Comment by marijn211** [comment]
Neither error seems crash-related, the Korea does seem fixed internally

**Comment by Thinking-waffle** [comment]
I made changes last patch.
