### ISSUE TITLE
Italy invasion puppet copies wars from fascist ITA

### ISSUE THREAD

**Issue by picturetheory** [deliciousmods/1956_beta#2887]
Playing a non-historical but RNGed mostly historical Trotsky SOV game. I was the first one into Italy. When the invasion puppet spawned, I was automatically at war with the Allies and Chinese United Front, with no popup saying I'd had war declared on me or notification that someone had been justifying on me. I reloaded the save in case I'd closed the popup by accident, and waited to see what would happen. The second time, the Allies triggered the invasion puppet, but I was again automatically at war with them. Again, there were no war declaration popups.

Looking at the "British-Soviet War" in each game, when I spawned the Italian puppet, the Allies and Chinese United Front were automatically at war with me. When the Allies spawned it, they were automatically at war with both me and the Chinese United Front. Again, there were no war declaration popups.

Screenshots of the war screens attached. I have the savegame files if needed.
![hoi4_w6AMWduKQK](https://github.com/deliciousmods/1956_beta/assets/508934/23c12ad9-2b73-4cf9-bcbc-0466eb056dc6)
![hoi4_Re2OG7eX1V](https://github.com/deliciousmods/1956_beta/assets/508934/71d8abbc-8aa3-4883-9052-1a4cef21d539)

**Comment by picturetheory** [comment]
On a historical UK playthrough, triggering the civil war puppet didn't cause a war with the Soviets. It also triggered much later than in RT56.

**Comment by marijn211** [comment]
Can't repro
