### ISSUE TITLE
Canada declares independence when reduce autonomy as Great Britain

### ISSUE THREAD

**Issue by Darpaek** [deliciousmods/1956_beta#2985]
Canada has an event "Declare Independence" that checks for 98% Autonomy, and this event fires when reducing Canada from a Dominion to a Colony because, as a colony, Canada suddenly has 100% autonomy when reduced.

I don't think this is working as intended.  The "Declare Independence" event for Canada may require an additional check that they are also a Dominion so it doesn't fire when Canada's autonomy is reduced.

**Comment by joshua-dean** [comment]
I believe this is the spot with the condition:
https://github.com/deliciousmods/1956_beta/blob/3235fc300bcf7ac4397c346fb4458437abfd879f/common/decisions/r56_generic_decisions.txt#L1124-L1127
