### ISSUE TITLE
Anatoly Pepelyayev's portrait

### ISSUE THREAD

**Issue by Symmachus** [deliciousmods/1956_beta#2993]
Anatoly Pepelyayev (one of the White Russian generals) currently uses this portrait: 
![r56_portrait_SOV_Anatoly_Pepelyaev](https://github.com/user-attachments/assets/84c43c3d-faf9-44c4-a0f6-1c784c404ff8)
The portrait is based on this photo taken in 1918,
![](https://upload.wikimedia.org/wikipedia/commons/c/cc/Analolij_Piepielajew.jpg)
with a lot of aging filters in order to make him look older. 
However, I've found a 1936 photo of him:
![Anatoliy-Pepelyaev-posle-aresta](https://github.com/user-attachments/assets/7ed74665-f043-4e00-ad3f-2a196e6dad73)
![161669269218526361](https://github.com/user-attachments/assets/f7b68007-da5b-4710-aa13-5fbd32e68589)
And I would like to suggest to redraw Pepelyayev's portrait based on it.

**Comment by TheBrit7** [comment]
Thanks for pointing it out. However, this is incredibly low on the priority list and most likely will not be done.
