### ISSUE TITLE
France Crash - Again

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#301]
user quote:

"Whenever I play france and go communist or fascist the usa immediately declares war on me in 1939 with a overthrow government wargoal, then a few months later crashes without fail. Feels extremely bad man"

**Comment by Greatexperiment** [comment]
Two more posts immediately after seem to verify this.

**Comment by SpicyAlfredo** [comment]
Can we just remove France from the game at this point lol

**Comment by SpicyAlfredo** [comment]
It has to be some kind of weird interaction between the trees that I can't find

**Comment by Tyguy9112** [comment]
Reply, if issue reoccurs.
