### ISSUE TITLE
Flag of Canada should be different

### ISSUE THREAD

**Issue by tobiasjcat** [deliciousmods/1956_beta#3034]
According to canada.ca the maple leaf flag didn't start being used until 1965. https://www.canada.ca/en/canadian-heritage/services/flag-canada-history.html

The flag used during WW2 was should be this one
https://commons.wikimedia.org/wiki/File:Flag_of_Canada_(1921%E2%80%931957).svg

**Comment by katsuragiyy** [comment]
The Dominion flag is already in use. it will only be used if Canada is fully independent.
