### ISSUE TITLE
Immersion breaking SS focus.

### ISSUE THREAD

**Issue by ghost** [deliciousmods/1956_beta#307]
Request for making it only possible to have Heinrich Himmler as an advisor after doing the german `GER_establish_SS` focus.

Also request for making certain SS unit names only available when you have Heinrich Himmler as an advisor with this simple line of code in the GER_names_divisions.txt file:

`can_use = { 
		has_government = fascism
		OR = {
			has_idea = heinrich_himmler
			has_country_leader = { name = "Heinrich Himmler" }
		}
	}`

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
