### ISSUE TITLE
Updating USSR focus tree.

### ISSUE THREAD

**Issue by Plutozz** [deliciousmods/1956_beta#313]
The mod we currently use Soviet Focus Rework has recently updated featuring some quite big changes. We don't have to include everything of course, but the major stuff from the update should most likely be added.

**Comment by Thinking-waffle** [comment]
and why the Trotskyist branch end with fascist counter coup anyway?

**Comment by Plutozz** [comment]
Even though the issues page is barley updated anymore. This was accomplished. Closing.
