### ISSUE TITLE
Updating German focus tree.

### ISSUE THREAD

**Issue by Plutozz** [deliciousmods/1956_beta#319]
The mod we currently use has updated quite a bit and has left ours very outdated (especially in it's alt-history paths). This is our most important focus tree, so we need to make sure that we get it right and also get rid of war crime references.

**Comment by Greatexperiment** [comment]
I would be very careful about this. Our tree has been heavily altered.

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
