### ISSUE TITLE
Fix the Warlords Fighting for the Chinese Government

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#320]
The integrated warlords are not transferred but instead generated (event china.101 in event/china). Some lack portraits (because pdx made a better one) and all lack detailed stats.
They should be tranferred from their clique governments instead, if they were "created" by the game before as commanders (see the personal rule focus of the warlord tree).

**Comment by Tyguy9112** [comment]
Reply, if issue reoccurs.
