### ISSUE TITLE
USA crash

### ISSUE THREAD

**Issue by Aviortheking** [deliciousmods/1956_beta#338]
When i go into the fachist USA my game always crash at jan 1940 on two differents parties

**Comment by SpicyAlfredo** [comment]
What was happening when you crashed?

**Comment by Aviorleking** [comment]
The game just close

**Comment by PordyHUN** [comment]
Is this issue live?

**Comment by Aviorleking** [comment]
I don't know I haven't played it in a while

**Comment by PordyHUN** [comment]
Thank you!

**Comment by Tyguy9112** [comment]
Is this still a bug going on?

**Comment by Aviortheking** [comment]
I have don't another play through and haven't had this crash again SSSI I thinks it's fixed?
