### ISSUE TITLE
Manchukuo locked out of focus tree.

### ISSUE THREAD

**Issue by ghost** [deliciousmods/1956_beta#383]
When the Japanese start the communist civil war and the communists loose, Manchukuo gets locked out of its main focus tree branch. This problem occurs on most of their political focuses since they check for the JAP tag.
Maybe add an additional OR condition consisting of checking if Japan still exists.

**Comment by Tyguy9112** [comment]
Is this still a problem occurring?

**Comment by Tyguy9112** [comment]
No Comment.
Will reopen if problem reoccurs.
