### ISSUE TITLE
Minor localization improvements - Netherlands

### ISSUE THREAD

**Issue by ccfox** [deliciousmods/1956_beta#492]
The Dutch communist path's description (HOL_communist_electoral_success_desc) is written an odd way; here is a rewrite that keeps basically the same meaning but cleans it up a bit:
The people have called for the demise of the corrupt tyranny by the bourgeois elite. Unemployment and poverty must end and the revolution triumph to ensure a bright future in which there will be no more classes - a future of true individual freedom.

I also took a stab at writing a description for the 'Red Volunteers' focus (HOL_red_volunteers) since it lacked one:
In order to further the cause of world revolution and proletarian internationalism we must be willing to aid all communist movements around the globe. Setting up a dedicated volunteer force to deploy and fight for the working class in foreign lands would be a good step towards this.

**Comment by PordyHUN** [comment]
Thank you for the contribution i added your things.
