### ISSUE TITLE
Manchukuo focus tree issues

### ISSUE THREAD

**Issue by HughJone** [deliciousmods/1956_beta#494]
With Jan. 8th mod:

1. "Strengthen The Royal Guard" does not bring 5 groups of Royal Guard for Manchukuo.
2. "Independence War" does not bring any RFP forces to Manchukuo's control.

**Comment by HughJone** [comment]
@Greatexperiment
Hello! How can I join the team for bug fixes? 
I know now I can just create a pull request by forking into my repo, but do you guys work like this or you will check membership first?

**Comment by PordyHUN** [comment]
Please contact me on discord server. Pordy#3912
I tagged you last time, but you dont answered.
We're appreciate your help. See you on Discord!
