### ISSUE TITLE
Companies are not assigning production bonuses

### ISSUE THREAD

**Issue by deliciousmods** [deliciousmods/1956_beta#6]
User quote:

"I realized that companies (specifically air in this case) weren't giving the bonuses to the newly added equipment (such as FIghter Bombers) After some digging I was able to fix the issue by moving 'r56e_traits.txt' from 'common\country_leader\replace' to 'common\country_leader' and renaming it to '00_r56e_traits.txt'"

This issue, if true, may need to be checked across 56 for all similar cases.

**Comment by Greatexperiment** [comment]
Files moved as suggested.
