### ISSUE TITLE
Assyrian Empire bug

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#62]
user report:

The Assyrian Empire has 2 Different areas in its focus tree in which it is able to demand colonial land from the UK and France, however only 1 of these parts where land is demanded do they gain cores, and they are unable to grain cores for the land demanded with the other part. Is this intended?

**Comment by Thinking-waffle** [comment]
Honestly it's one of the ambitious but very bad trees. It makes the country behave wildly and make insane demands while disregarding the historical background which is fun and interesting.

**Comment by Greatexperiment** [comment]
Fixed for now, but should have the AI overhauled later.
