### ISSUE TITLE
France has a problem with communism if it tries to change the matignon agreements

### ISSUE THREAD

**Issue by Thinking-waffle** [deliciousmods/1956_beta#85]
They begin at 50-50 but if you change the matignon agreement they get 20% communism and civil war becomes inevitable. In addition it locks their political tree. Huzzah for great design.
I changed the communist bonus to a loss of stability.

**Comment by Greatexperiment** [comment]
There's an earlier open issue on this, and it should be closed at the same time once this is solved.

**Comment by Zurich899** [comment]
I'm not sure when this changed, but France doesn't start at 50/50 communism / democratic any more. They are now 30 / 70 communism / democratic, and this lowered starting communism will probably make the civil war less inevitable. I'm also playing with the French political focus tree, and it seems to be fine now that the Matignon Agreement focuses were changed.

**Comment by Tyguy9112** [comment]
Reply, if you want reopened
