### ISSUE TITLE
Ruthenia / Czech bug

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#94]
user quote:

Playing as Austria there is a game breaking bug that currenlty exists. If any form of the Ruthenian state has fromed from Czechoslovakia then the request slovakia focus for Austria doesn't actually don anything. You can request slovakia and the Germans can say yes but it does nothing. I recived the notification saying that Germany had accepted the proposal but nothing happend. I let hte game run for a little while to see if it just needed time to kick in but the even never actualy did anything. 

And just to clarify. I'm running the current build of the game and the mod. I'm not running any other mods at the same time. This problem first was noticed in a multiplayer game and then I tried to replicate it tonight in single player and the same problem occured.

**Comment by Tyguy9112** [comment]
Reply, if issue reoccurs.
