### ISSUE TITLE
Update some leader portraits (if they haven't been already)

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#95]
user quote:

Leader portraits for iraq, mongolia and latin american countries are not updated and japan's democratic and communist portraits still use the generic ones.

p.s. I think I did these already, but it's worth checking again.

**Comment by Zurich899** [comment]
Thanks for merging the pulls I made yesterday. Now that all the new portraits have been confirmed, I think that this issue can be closed.

**Comment by Greatexperiment** [comment]
Sure. I appreciate the work.
