### ISSUE TITLE
Import Blendheims bug

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#98]
user quote:

The Import Blendheims national focus of Finland gives research bonus to german Me110s.

**Comment by Zurich899** [comment]
This isn't exactly a bug, but I can understand why this user thought it was. The focus works as expected, but the Blendheim import and license production do not appear in the focus's effect until the United Kingdom has researched heavy fighters. I modified two files to add a tooltip which explains this to the user and improved the Import Blendheim focus's description, which should remove any confusion about this focus's effect.

**Comment by Greatexperiment** [comment]
Thanks for doing this.

**Comment by Zurich899** [comment]
No problem, but double check like 3008 on the focus tree. The search in Github is inconsistent, and I may have accidentally added some spaces to the technology = heavy_battleship line. (Sorry about that, still new to Github)
