### ISSUE TITLE
Check Maintenance Companies

### ISSUE THREAD

**Issue by Greatexperiment** [deliciousmods/1956_beta#99]
user quote:

Currently mantinence companies don't give extra capture bonuses like in the main game, and only give reliability bonus. Is this intentional?

**Comment by Zurich899** [comment]
I just checked the maintenance companies in-game and in the files. Road to 56 does not modify maintenance companies at all, and their stats were carried over from Vanilla. I can confirm that maintenance companies are adding a +5% equipment capture bonus as expected, and this issue can be closed.
![hoi4_7](https://user-images.githubusercontent.com/13583641/38466973-ab64aa6a-3b5b-11e8-98ab-2107102c0ab2.png)

**Comment by Greatexperiment** [comment]
Thanks for checking it out.
